# Generated by Django 4.2.16 on 2024-10-01 15:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0002_post_exerpt'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='update_on',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
